FROM mcr.microsoft.com/dotnet/aspnet:5.0
RUN dotnet publish -c Debug
COPY bin/Debug/net5.0/publish/ SALT.WebApi.Template/
WORKDIR /SALT.WebApi.Template
ENTRYPOINT ["dotnet", "NetCore.Docker.dll"]
EXPOSE 9000