FROM mcr.microsoft.com/dotnet/aspnet:latest
RUN dotnet publish -c Release
COPY bin/Release/net7.0/publish/ SALT.WebApi.Template/
WORKDIR /SALT.WebApi.Template
ENTRYPOINT ["dotnet", "NetCore.Docker.dll"]
EXPOSE 9000